### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by xsd0720** [se4/cddh#2]
>>> import pytesseract
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/pytesseract/__init__.py", line 2, in <module>
    from pytesseract import image_to_string
  File "/Library/Python/2.7/site-packages/pytesseract/pytesseract.py", line 9, in <module>
    import Image
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 27, in <module>
    from . import VERSION, PILLOW_VERSION, _plugins
ValueError: Attempted relative import in non-package

**Comment by se4** [comment]
emmm . .python2.7..可能是pytesseract没装好吧，所以没法导入模块

```
easy_install Pillow
easy_install pytesseract
```

上网搜搜吧
